-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create Enum Types
DO $$ BEGIN
    CREATE TYPE lead_status AS ENUM ('new', 'qualified', 'converted', 'archived');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE ticket_status AS ENUM ('open', 'in_progress', 'resolved', 'closed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE ticket_type AS ENUM ('install', 'repair', 'maintenance');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'runner', 'viewer');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Create Tables

-- Villages (Locations)
create table if not exists public.villages (
  id bigint generated by default as identity primary key,
  name text not null,
  region text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Profiles (Users - linked to Auth)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  role user_role default 'runner',
  phone_number text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Leads (Incoming from WhatsApp)
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  whatsapp_id text unique not null,
  customer_name text,
  village_id bigint references public.villages(id),
  status lead_status default 'new'::lead_status,
  interest_level integer default 0,
  notes text,
  last_interaction_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tickets (Jobs)
create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  lead_id bigint references public.leads(id),
  assigned_to uuid references public.profiles(id),
  type ticket_type default 'install'::ticket_type,
  status ticket_status default 'open'::ticket_status,
  description text,
  location_gps text,
  scheduled_for timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ticket Photos
create table if not exists public.ticket_photos (
  id bigint generated by default as identity primary key,
  ticket_id bigint references public.tickets(id),
  storage_path text not null,
  caption text,
  uploaded_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Row Level Security (RLS)
alter table public.villages enable row level security;
alter table public.profiles enable row level security;
alter table public.leads enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_photos enable row level security;

-- Policies (Permissive for MVP development - tighten before prod)
create policy "Enable read access for all users" on public.villages for select using (true);
create policy "Enable read access for all users" on public.profiles for select using (true);

-- Leads: Authenticated users (Admin/Runners) can view all
create policy "Authenticated users can view leads" on public.leads for select using (auth.role() = 'authenticated');
create policy "Authenticated users can update leads" on public.leads for update using (auth.role() = 'authenticated');

-- Tickets: Authenticated users can view/update
create policy "Authenticated users can view tickets" on public.tickets for select using (auth.role() = 'authenticated');
create policy "Authenticated users can update tickets" on public.tickets for update using (auth.role() = 'authenticated');

-- Storage Bucket (Create via SQL if possible, otherwise manual)
insert into storage.buckets (id, name, public) values ('photos', 'photos', true) on conflict (id) do nothing;
create policy "Public Access" on storage.objects for select using ( bucket_id = 'photos' );
create policy "Authenticated Insert" on storage.objects for insert with check ( bucket_id = 'photos' and auth.role() = 'authenticated' );
