-- Pricing Rules Table
-- Stores pricing rules for the offer engine

create table public.pricing_rules (
  id bigint generated by default as identity primary key,
  rule_name text not null,
  condition_type text not null, -- 'excellent', 'good', 'fair', 'poor'
  base_price numeric(10, 2) not null,
  village_id bigint references public.villages(id) on delete set null, -- null = applies to all villages
  multiplier numeric(5, 2) default 1.0, -- multiplier for base price
  min_price numeric(10, 2),
  max_price numeric(10, 2),
  active boolean default true,
  priority integer default 0, -- higher priority rules are applied first
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
alter table public.pricing_rules enable row level security;

-- RLS Policy: Service role can manage all pricing rules
create policy "Service role manages pricing rules" 
  on public.pricing_rules 
  for all 
  using (true);

-- Index for quick lookups
create index idx_pricing_rules_condition on public.pricing_rules(condition_type, active);
create index idx_pricing_rules_village on public.pricing_rules(village_id) where village_id is not null;

-- Function to update updated_at timestamp
create or replace function update_pricing_rules_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger to auto-update updated_at
create trigger update_pricing_rules_updated_at
  before update on public.pricing_rules
  for each row
  execute function update_pricing_rules_updated_at();

-- Default pricing rules
insert into public.pricing_rules (rule_name, condition_type, base_price, multiplier, priority) values
  ('Excellent Condition - Default', 'excellent', 800.00, 1.5, 10),
  ('Good Condition - Default', 'good', 600.00, 1.2, 10),
  ('Fair Condition - Default', 'fair', 400.00, 0.8, 10),
  ('Poor Condition - Default', 'poor', 250.00, 0.5, 10)
on conflict do nothing;
