-- Consolidated Fridge Workflow Schema
-- This migration consolidates and replaces previous conflicting schemas

-- Enable extensions
create extension if not exists "uuid-ossp";

-- Drop existing tables to start clean
drop table if exists public.ticket_photos cascade;
drop table if exists public.tickets cascade;
drop table if exists public.leads cascade;
drop table if exists public.profiles cascade;
drop table if exists public.villages cascade;

-- Drop existing types
drop type if exists lead_status cascade;
drop type if exists ticket_status cascade;
drop type if exists ticket_type cascade;
drop type if exists user_role cascade;

-- Create enum types
create type lead_status as enum ('new', 'qualified', 'converted', 'archived');
create type ticket_status as enum ('open', 'assigned', 'in_progress', 'completed', 'closed');
create type ticket_type as enum ('sell', 'repair', 'maintenance');
create type user_role as enum ('admin', 'runner');

-- Villages table
create table public.villages (
  id bigint generated by default as identity primary key,
  name text not null,
  region text,
  active boolean default true,
  created_at timestamp with time zone default now()
);

-- User profiles
create table public.profiles (
  id uuid references auth.users primary key,
  full_name text,
  role user_role default 'runner',
  phone_number text,
  created_at timestamp with time zone default now()
);

-- Leads from WhatsApp
create table public.leads (
  id bigint generated by default as identity primary key,
  whatsapp_id text unique not null,
  customer_name text,
  phone_number text,
  village_id bigint references public.villages(id),
  status lead_status default 'new',
  notes text,
  created_at timestamp with time zone default now()
);

-- Tickets (jobs/tasks)
create table public.tickets (
  id uuid default gen_random_uuid() primary key,
  lead_id bigint references public.leads(id),
  fridge_code text not null,
  category text not null, -- 'sell' or 'repair'
  type ticket_type default 'sell',
  status ticket_status default 'open',
  description text,
  assigned_to uuid references public.profiles(id),
  location_gps text,
  image_url text,
  scheduled_for timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- Photo storage
create table public.ticket_photos (
  id bigint generated by default as identity primary key,
  ticket_id uuid references public.tickets(id) on delete cascade,
  storage_path text not null,
  caption text,
  uploaded_by uuid references public.profiles(id),
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table public.villages enable row level security;
alter table public.profiles enable row level security;
alter table public.leads enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_photos enable row level security;

-- RLS Policies
create policy "Public read villages" on public.villages for select using (true);
create policy "Public read profiles" on public.profiles for select using (true);

create policy "Auth users manage leads" on public.leads for all using (auth.role() = 'authenticated');
create policy "Auth users manage tickets" on public.tickets for all using (auth.role() = 'authenticated');
create policy "Auth users manage photos" on public.ticket_photos for all using (auth.role() = 'authenticated');

-- Storage bucket
insert into storage.buckets (id, name, public) values ('photos', 'photos', true) on conflict do nothing;
create policy "Public read photos" on storage.objects for select using (bucket_id = 'photos');
create policy "Auth upload photos" on storage.objects for insert with check (bucket_id = 'photos' and auth.role() = 'authenticated');

-- Sample data
insert into public.villages (name, region) values 
  ('Soweto', 'Gauteng'),
  ('Alexandra', 'Gauteng'),
  ('Diepsloot', 'Gauteng')
on conflict do nothing;